### ISSUE TITLE
Custom pattern not working

### ISSUE THREAD

**Issue by nhoxbypass** [Annihil/github-spray#2]
I use Github Spray Generator to generate custom pattern. In the README it said that 

> The numbers (1 to 4) will determine the green's darkness.

But in my case, the numbers determine the **number of commit per day**, so I cannot use the darkest color (because number of commit must be > 10 per day to achieve this).

**Comment by Annihil** [comment]
True that, I'll clarify this asap,
thanks for the feedback 🙂
