### ISSUE TITLE
Commits not found for user...

### ISSUE THREAD

**Issue by yiran7324** [Annihil/github-spray#8]
Hi there,

When I tried to check the individual commit through profile->graph->green grid generated by github-spray->commits, I got the message "No commits found for "user" (using user@gmail.com)". Any solutions to this?

Thx.

**Comment by Annihil** [comment]
Can you ensure that you can use `git` in command line to push to Github in the first place?

**Comment by yiran7324** [comment]
Should it be done with "git" in command line purely, I came to find all my commits dating at previous stamp didn't show correctly in github, with or without the version of client of git.

**Comment by Annihil** [comment]
No it shouldn't, but it is to be sure that at least `git` is working fine in the first place

**Comment by yiran7324** [comment]
OK, may it be the bug with hub itself. Thx.
