### ISSUE TITLE
Commits are dated as the day and time that the command run.

### ISSUE THREAD

**Issue by fatimaavilesfa** [Annihil/github-spray#9]
I follow the instructions first `npm i -g github-spray` created a repo and then run `github-spray -t hello --multiplier 10 --push --origin https://github.com/fatimaavilesfa/spray.git` and all the commits show same commit time.

![commits1](https://user-images.githubusercontent.com/40034956/94977091-807a2b00-04d4-11eb-8deb-59bd2e517f1e.png)

And going throg the commits all show the same time

![allcommits](https://user-images.githubusercontent.com/40034956/94977136-a9022500-04d4-11eb-9496-3ee9410136de.png)

The time on the commits should show different dates.
`

**Comment by seisvelas** [comment]
Same problem for me: https://github.com/seisvelas/spray/

**Comment by seisvelas** [comment]
Oh, weird, it finally started showing up for me, although it appears to never have showed up for @fatimaavilesfa
